### ISSUE TITLE
Cache StdLib Cpp intermediate files for faster test times

### ISSUE THREAD

**Issue by 0b1kn00b** [kiss-lang/kiss#17]
I'm running [act](https://github.com/nektos/act) in order to run github actions locally, and I've found that caching cpp std library output would improve the speed no end.

The only thing is, in order to invalidate the cache reliably, we'd need the hxcpp version checked in in `haxe_libraries` so that the hash changes when the version changes.

Here's the action invocation that I've cobbled together, I've dropped it in at the first step.

```yml
      - name: Cache Cpp Intermediate Files
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/bin/cpp/test
          key: haxe-${{runner.os}}-hxcpp-${{hashFiles('.haxerc', 'haxe_libraries/*.hxml')}}
          restore-keys: haxe-${{runner.os}}-hxcpp-
```
